src/java/com/ParqueaderoV1/controlador/ParquedoController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ParqueaderoV1.controlador;

import com.ParqueaderoV1.controlador.util.JsfUtil;
import com.ParqueaderoV1.controlador.util.PaginationHelper;
import com.ParqueaderoV1.modelo.entidad.Parquedo;
import com.ParqueaderoV1.modelo.facades.ParquedoFacadeLocal;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

/**
 *
 * @author alejo
 */
@Named(value = "parquedoController")
@SessionScoped
public class ParquedoController implements Serializable {

    @EJB
    private ParquedoFacadeLocal ufl;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    private Parquedo current;
    private DataModel items = null;
    public ParquedoController() {
    }

    @PostConstruct
    public void init() {

    }

    public List<Parquedo> listar() {

        List<Parquedo> parqueos = ufl.findAll();

        return parqueos;

    }
    
        public int contar() {

        int contar = ufl.count();

        return contar;

    }

    public Parquedo getSelected() {
        if (current == null) {
            current = new Parquedo();
            selectedItemIndex = -1;
        }
        return current;
    }

    private ParquedoFacadeLocal getFacade() {
        return ufl;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Parquedo) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Parquedo();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/parametros").getString("ParquedoCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/parametros").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Parquedo) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/parametros").getString("ParquedoUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/parametros").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Parquedo) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/parametros").getString("ParquedoDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/parametros").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ufl.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ufl.findAll(), true);
    }

    public Parquedo getParquedo(java.lang.Integer id) {
        return ufl.find(id);
    }

    @FacesConverter(forClass = Parquedo.class)
    public static class ParquedoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ParquedoController controller = (ParquedoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "parquedoController");
            return controller.getParquedo(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Parquedo) {
                Parquedo o = (Parquedo) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Parquedo.class.getName());
            }
        }

    }
}

web/parquedo/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:atr="http://xmlns.jcp.org/jsf/passthrough">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{parametros.CreateParquedoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <script>
                $(document).ready(function () {
                    $('select').material_select();
                });
            </script>
            <div class="row">

                <h:form class="col s12">
                    <div class="row" >
                        <div class="input-field col s4">
                            <h:outputLabel value="#{parametros.CreateParquedoLabel_id}" for="id" />
                            <br/>
                            <h:inputText id="id" value="#{parquedoController.selected.id}" title="#{parametros.CreateParquedoTitle_id}" required="true" requiredMessage="#{parametros.CreateParquedoRequiredMessage_id}"/>
                        </div>
                        <div class="input-field col s4">
                           
                            <h:outputLabel value="#{parametros.CreateParquedoLabel_entrada}" for="entrada" />
                            <br/>
                            <h:inputText class="datepicker" atr:type="datetime-local" id="entrada" value="#{parquedoController.selected.entrada}" title="#{parametros.CreateParquedoTitle_entrada}" >
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:inputText>
                        </div>
                        <div class="input-field col s4">
                            <h:outputLabel value="#{parametros.CreateParquedoLabel_salida}" for="salida" />
                            <br/>
                            <h:inputText class="datepicker" atr:type="datetime-local" id="salida" value="#{parquedoController.selected.salida}" title="#{parametros.CreateParquedoTitle_salida}" >
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:inputText>
                        </div>
                        <div class="input-field col s4">
                            <h:outputLabel value="#{parametros.CreateParquedoLabel_minutos}" for="minutos" />
                            <br/>
                            <h:inputText id="minutos" value="#{parquedoController.selected.minutos}" title="#{parametros.CreateParquedoTitle_minutos}" />
                        </div>
                        <div class="input-field col s4">
                            <h:outputLabel value="#{parametros.CreateParquedoLabel_valor}" for="valor" />
                            <br/>
                            <h:inputText id="valor" value="#{parquedoController.selected.valor}" title="#{parametros.CreateParquedoTitle_valor}" />
                        </div>
                        <div class="input-field col s4">
                            <h:outputLabel value="#{parametros.CreateParquedoLabel_idVehiculo}" for="idVehiculo" />
                            <br/>
                            <h:selectOneMenu id="idVehiculo" value="#{parquedoController.selected.idVehiculo}" title="#{parametros.CreateParquedoTitle_idVehiculo}" >
                                <f:selectItems value="#{vehiculosController.itemsAvailableSelectOne}"/>
                            </h:selectOneMenu>
                        </div>
                        <div class="input-field col s4">
                            <h:outputLabel value="#{parametros.CreateParquedoLabel_idCupo}" for="idCupo" />
                            <br/>
                            <h:selectOneMenu id="idCupo" value="#{parquedoController.selected.idCupo}" title="#{parametros.CreateParquedoTitle_idCupo}" >
                                <f:selectItems value="#{cupoController.itemsAvailableSelectOne}"/>
                            </h:selectOneMenu>
                        </div>
                    </div>
                    <div class=" col s12">
                        <div class="col s4">
                            <h:commandLink class="btn waves-effect waves-light" action="#{parquedoController.create}" value="#{parametros.CreateParquedoSaveLink}" />
                        </div>
                        <div class="col s4">
                            <h:commandLink class="btn waves-effect green darken-1" action="#{parquedoController.prepareList}" value="#{parametros.CreateParquedoShowAllLink}" immediate="true"/>
                        </div>
                        <div class="col s4">
                            <h:link class="btn waves-effect  lime darken-1" outcome="/index" value="#{parametros.CreateParquedoIndexLink}"/>
                        </div>
                    </div>
                </h:form>
            </div>



        </ui:define>
    </ui:composition>

</html>

web/parquedo/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{parametros.EditParquedoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{parametros.EditParquedoLabel_id}" for="id" />
                    <h:inputText id="id" value="#{parquedoController.selected.id}" title="#{parametros.EditParquedoTitle_id}" required="true" requiredMessage="#{parametros.EditParquedoRequiredMessage_id}"/>
                    <h:outputLabel value="#{parametros.EditParquedoLabel_entrada}" for="entrada" />
                    <h:inputText id="entrada" value="#{parquedoController.selected.entrada}" title="#{parametros.EditParquedoTitle_entrada}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{parametros.EditParquedoLabel_salida}" for="salida" />
                    <h:inputText id="salida" value="#{parquedoController.selected.salida}" title="#{parametros.EditParquedoTitle_salida}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{parametros.EditParquedoLabel_minutos}" for="minutos" />
                    <h:inputText id="minutos" value="#{parquedoController.selected.minutos}" title="#{parametros.EditParquedoTitle_minutos}" />
                    <h:outputLabel value="#{parametros.EditParquedoLabel_valor}" for="valor" />
                    <h:inputText id="valor" value="#{parquedoController.selected.valor}" title="#{parametros.EditParquedoTitle_valor}" />
                    <h:outputLabel value="#{parametros.EditParquedoLabel_idVehiculo}" for="idVehiculo" />
                    <h:selectOneMenu id="idVehiculo" value="#{parquedoController.selected.idVehiculo}" title="#{parametros.EditParquedoTitle_idVehiculo}" >
                        <f:selectItems value="#{vehiculosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{parametros.EditParquedoLabel_idCupo}" for="idCupo" />
                    <h:selectOneMenu id="idCupo" value="#{parquedoController.selected.idCupo}" title="#{parametros.EditParquedoTitle_idCupo}" >
                        <f:selectItems value="#{cupoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{parquedoController.update}" value="#{parametros.EditParquedoSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{parametros.EditParquedoViewLink}"/>
                <br />
                <h:commandLink action="#{parquedoController.prepareList}" value="#{parametros.EditParquedoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{parametros.EditParquedoIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/parquedo/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{parametros.ListParquedoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{parametros.ListParquedoEmpty}" rendered="#{parquedoController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{parquedoController.items.rowCount > 0}">
                    <h:outputText value="#{parquedoController.pagination.pageFirstItem + 1}..#{parquedoController.pagination.pageLastItem + 1}/#{parquedoController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{parquedoController.previous}" value="#{parametros.Previous} #{parquedoController.pagination.pageSize}" rendered="#{parquedoController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{parquedoController.next}" value="#{parametros.Next} #{parquedoController.pagination.pageSize}" rendered="#{parquedoController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{parquedoController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametros.ListParquedoTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametros.ListParquedoTitle_entrada}"/>
                            </f:facet>
                            <h:outputText value="#{item.entrada}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametros.ListParquedoTitle_salida}"/>
                            </f:facet>
                            <h:outputText value="#{item.salida}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametros.ListParquedoTitle_minutos}"/>
                            </f:facet>
                            <h:outputText value="#{item.minutos}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametros.ListParquedoTitle_valor}"/>
                            </f:facet>
                            <h:outputText value="#{item.valor}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametros.ListParquedoTitle_idVehiculo}"/>
                            </f:facet>
                            <h:outputText value="#{item.idVehiculo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametros.ListParquedoTitle_idCupo}"/>
                            </f:facet>
                            <h:outputText value="#{item.idCupo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{parquedoController.prepareView}" value="#{parametros.ListParquedoViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{parquedoController.prepareEdit}" value="#{parametros.ListParquedoEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{parquedoController.destroy}" value="#{parametros.ListParquedoDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{parquedoController.prepareCreate}" value="#{parametros.ListParquedoCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{parametros.ListParquedoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/parquedo/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{parametros.ViewParquedoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{parametros.ViewParquedoLabel_id}"/>
                    <h:outputText value="#{parquedoController.selected.id}" title="#{parametros.ViewParquedoTitle_id}"/>
                    <h:outputText value="#{parametros.ViewParquedoLabel_entrada}"/>
                    <h:outputText value="#{parquedoController.selected.entrada}" title="#{parametros.ViewParquedoTitle_entrada}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{parametros.ViewParquedoLabel_salida}"/>
                    <h:outputText value="#{parquedoController.selected.salida}" title="#{parametros.ViewParquedoTitle_salida}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{parametros.ViewParquedoLabel_minutos}"/>
                    <h:outputText value="#{parquedoController.selected.minutos}" title="#{parametros.ViewParquedoTitle_minutos}"/>
                    <h:outputText value="#{parametros.ViewParquedoLabel_valor}"/>
                    <h:outputText value="#{parquedoController.selected.valor}" title="#{parametros.ViewParquedoTitle_valor}"/>
                    <h:outputText value="#{parametros.ViewParquedoLabel_idVehiculo}"/>
                    <h:outputText value="#{parquedoController.selected.idVehiculo}" title="#{parametros.ViewParquedoTitle_idVehiculo}"/>
                    <h:outputText value="#{parametros.ViewParquedoLabel_idCupo}"/>
                    <h:outputText value="#{parquedoController.selected.idCupo}" title="#{parametros.ViewParquedoTitle_idCupo}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{parquedoController.destroyAndView}" value="#{parametros.ViewParquedoDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{parametros.ViewParquedoEditLink}"/>
                <br />
                <h:commandLink action="#{parquedoController.prepareCreate}" value="#{parametros.ViewParquedoCreateLink}" />
                <br />
                <h:commandLink action="#{parquedoController.prepareList}" value="#{parametros.ViewParquedoShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{parametros.ViewParquedoIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>